<?php

declare(strict_types=1);

/**
 * VodaPay Gateway
 *
 * Enabling ecommerce merchants to accept online payments from customers.
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VodaPayGatewayClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use VodaPayGatewayClient\ApiException;
use VodaPayGatewayClient\Configuration;
use VodaPayGatewayClient\HeaderSelector;
use VodaPayGatewayClient\ObjectSerializer;

class PayApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'payCompleteOnceOff' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'payOnceOff' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'payRecurring' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'payRefund' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'paySubmitRecurring' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * payCompleteOnceOff: Complete payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPaymentComplete $model VodaPayGatewayPaymentComplete. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payCompleteOnceOff'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse|\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse
     */
    public function payCompleteOnceOff(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payCompleteOnceOff'][0],
    ): mixed {
        list($response) = $this->payCompleteOnceOffWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * payCompleteOnceOffWithHttpInfo: Complete payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPaymentComplete $model VodaPayGatewayPaymentComplete. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payCompleteOnceOff'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse|\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function payCompleteOnceOffWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payCompleteOnceOff'][0],
    ): array {
        $request = $this->payCompleteOnceOffRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * payCompleteOnceOffAsync: Complete payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPaymentComplete $model VodaPayGatewayPaymentComplete. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payCompleteOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payCompleteOnceOffAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payCompleteOnceOff'][0],
    ): PromiseInterface {
        return $this->payCompleteOnceOffAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * payCompleteOnceOffAsyncWithHttpInfo: Complete payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPaymentComplete $model VodaPayGatewayPaymentComplete. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payCompleteOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payCompleteOnceOffAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payCompleteOnceOff'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayCompleteResponse';
        $request = $this->payCompleteOnceOffRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'payCompleteOnceOff'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPaymentComplete $model VodaPayGatewayPaymentComplete. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payCompleteOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payCompleteOnceOffRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payCompleteOnceOff'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling payCompleteOnceOff'
            );
        }



        $resourcePath = '/v2/Pay/CompleteOnceOff';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * payOnceOff: Immediate payment intent.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPayment $model VodaPayGatewayPayment. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test The testing flag. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payOnceOff'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayResponse|\VodaPayGatewayClient\Model\VodaPayGatewayResponse
     */
    public function payOnceOff(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payOnceOff'][0],
    ): mixed {
        list($response) = $this->payOnceOffWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * payOnceOffWithHttpInfo: Immediate payment intent.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPayment $model VodaPayGatewayPayment. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test The testing flag. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payOnceOff'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayResponse|\VodaPayGatewayClient\Model\VodaPayGatewayResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function payOnceOffWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payOnceOff'][0],
    ): array {
        $request = $this->payOnceOffRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * payOnceOffAsync: Immediate payment intent.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPayment $model VodaPayGatewayPayment. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test The testing flag. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payOnceOffAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payOnceOff'][0],
    ): PromiseInterface {
        return $this->payOnceOffAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * payOnceOffAsyncWithHttpInfo: Immediate payment intent.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPayment $model VodaPayGatewayPayment. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test The testing flag. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payOnceOffAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payOnceOff'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayResponse';
        $request = $this->payOnceOffRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'payOnceOff'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayPayment $model VodaPayGatewayPayment. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test The testing flag. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payOnceOff'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payOnceOffRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payOnceOff'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling payOnceOff'
            );
        }



        $resourcePath = '/v2/Pay/OnceOff';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * payRecurring: Create recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurring $model VodaPayGatewayRecurring. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRecurring'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayResponse|\VodaPayGatewayClient\Model\VodaPayGatewayResponse
     */
    public function payRecurring(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRecurring'][0],
    ): mixed {
        list($response) = $this->payRecurringWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * payRecurringWithHttpInfo: Create recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurring $model VodaPayGatewayRecurring. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRecurring'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayResponse|\VodaPayGatewayClient\Model\VodaPayGatewayResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function payRecurringWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRecurring'][0],
    ): array {
        $request = $this->payRecurringRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * payRecurringAsync: Create recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurring $model VodaPayGatewayRecurring. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRecurringAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRecurring'][0],
    ): PromiseInterface {
        return $this->payRecurringAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * payRecurringAsyncWithHttpInfo: Create recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurring $model VodaPayGatewayRecurring. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRecurringAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRecurring'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayResponse';
        $request = $this->payRecurringRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'payRecurring'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurring $model VodaPayGatewayRecurring. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRecurringRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRecurring'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling payRecurring'
            );
        }



        $resourcePath = '/v2/Pay/Recurring';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * payRefund: Immediate refund.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRefund $model VodaPayGatewayRefund. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRefund'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse|\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse
     */
    public function payRefund(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRefund'][0],
    ): mixed {
        list($response) = $this->payRefundWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * payRefundWithHttpInfo: Immediate refund.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRefund $model VodaPayGatewayRefund. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRefund'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse|\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function payRefundWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRefund'][0],
    ): array {
        $request = $this->payRefundRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * payRefundAsync: Immediate refund.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRefund $model VodaPayGatewayRefund. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRefundAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRefund'][0],
    ): PromiseInterface {
        return $this->payRefundAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * payRefundAsyncWithHttpInfo: Immediate refund.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRefund $model VodaPayGatewayRefund. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRefundAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRefund'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayRefundResponse';
        $request = $this->payRefundRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'payRefund'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRefund $model VodaPayGatewayRefund. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['payRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function payRefundRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['payRefund'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling payRefund'
            );
        }



        $resourcePath = '/v2/Pay/Refund';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * paySubmitRecurring: Submit recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurringSubmit $model VodaPayGatewayRecurringSubmit. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paySubmitRecurring'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse|\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse
     */
    public function paySubmitRecurring(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['paySubmitRecurring'][0],
    ): mixed {
        list($response) = $this->paySubmitRecurringWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * paySubmitRecurringWithHttpInfo: Submit recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurringSubmit $model VodaPayGatewayRecurringSubmit. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paySubmitRecurring'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse|\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function paySubmitRecurringWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['paySubmitRecurring'][0],
    ): array {
        $request = $this->paySubmitRecurringRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * paySubmitRecurringAsync: Submit recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurringSubmit $model VodaPayGatewayRecurringSubmit. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paySubmitRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function paySubmitRecurringAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['paySubmitRecurring'][0],
    ): PromiseInterface {
        return $this->paySubmitRecurringAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * paySubmitRecurringAsyncWithHttpInfo: Submit recurring payment.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurringSubmit $model VodaPayGatewayRecurringSubmit. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paySubmitRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function paySubmitRecurringAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['paySubmitRecurring'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewaySubmitRecurringResponse';
        $request = $this->paySubmitRecurringRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paySubmitRecurring'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayRecurringSubmit $model VodaPayGatewayRecurringSubmit. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paySubmitRecurring'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function paySubmitRecurringRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['paySubmitRecurring'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling paySubmitRecurring'
            );
        }



        $resourcePath = '/v2/Pay/SubmitRecurring';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
