<?php

declare(strict_types=1);

/**
 * VodaPay Gateway
 *
 * Enabling ecommerce merchants to accept online payments from customers.
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VodaPayGatewayClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use VodaPayGatewayClient\ApiException;
use VodaPayGatewayClient\Configuration;
use VodaPayGatewayClient\HeaderSelector;
use VodaPayGatewayClient\ObjectSerializer;

class TokenApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'tokenAuthenticate' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'tokenControl' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'tokenCreate' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'tokenList' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * tokenAuthenticate: Initiate authentication of token
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayAuthenticateToken $model VodaPayGatewayTokenResponse. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenAuthenticate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse
     */
    public function tokenAuthenticate(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenAuthenticate'][0],
    ): mixed {
        list($response) = $this->tokenAuthenticateWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * tokenAuthenticateWithHttpInfo: Initiate authentication of token
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayAuthenticateToken $model VodaPayGatewayTokenResponse. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenAuthenticate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function tokenAuthenticateWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenAuthenticate'][0],
    ): array {
        $request = $this->tokenAuthenticateRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * tokenAuthenticateAsync: Initiate authentication of token
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayAuthenticateToken $model VodaPayGatewayTokenResponse. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenAuthenticate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenAuthenticateAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenAuthenticate'][0],
    ): PromiseInterface {
        return $this->tokenAuthenticateAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * tokenAuthenticateAsyncWithHttpInfo: Initiate authentication of token
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayAuthenticateToken $model VodaPayGatewayTokenResponse. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenAuthenticate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenAuthenticateAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenAuthenticate'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
        $request = $this->tokenAuthenticateRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenAuthenticate'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayAuthenticateToken $model VodaPayGatewayTokenResponse. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenAuthenticate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenAuthenticateRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenAuthenticate'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling tokenAuthenticate'
            );
        }



        $resourcePath = '/v2/Token/Authenticate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * tokenControl
     *
     * @param  string $control control (required)
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayToken $model model (required)
     * @param  string $api_key api_key (optional)
     * @param  bool $test test (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenControl'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse
     */
    public function tokenControl(
        mixed $control,
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenControl'][0],
    ): mixed {
        list($response) = $this->tokenControlWithHttpInfo($control, $model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * tokenControlWithHttpInfo
     *
     * @param  string $control (required)
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayToken $model (required)
     * @param  string $api_key (optional)
     * @param  bool $test (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenControl'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function tokenControlWithHttpInfo(
        mixed $control,
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenControl'][0],
    ): array {
        $request = $this->tokenControlRequest($control, $model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * tokenControlAsync
     *
     * @param  string $control (required)
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayToken $model (required)
     * @param  string $api_key (optional)
     * @param  bool $test (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenControl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenControlAsync(
        mixed $control,
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenControl'][0],
    ): PromiseInterface {
        return $this->tokenControlAsyncWithHttpInfo($control, $model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * tokenControlAsyncWithHttpInfo
     *
     * @param  string $control (required)
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayToken $model (required)
     * @param  string $api_key (optional)
     * @param  bool $test (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenControl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenControlAsyncWithHttpInfo(
        mixed $control,
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenControl'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
        $request = $this->tokenControlRequest($control, $model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenControl'
     *
     * @param  string $control (required)
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayToken $model (required)
     * @param  string $api_key (optional)
     * @param  bool $test (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenControl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenControlRequest(
        mixed $control,
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenControl'][0],
    ): Request {
        // verify the required parameter 'control' is set
        if ($control === null || (is_array($control) && count($control) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $control when calling tokenControl'
            );
        }

        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling tokenControl'
            );
        }



        $resourcePath = '/v2/Token/{control}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        // path params
        if ($control !== null) {
            $resourcePath = str_replace(
                '{' . 'control' . '}',
                ObjectSerializer::toPathValue($control),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * tokenCreate: Create the specified model.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayCreateToken $model VodaPayGatewayCreateToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenCreate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse
     */
    public function tokenCreate(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenCreate'][0],
    ): mixed {
        list($response) = $this->tokenCreateWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * tokenCreateWithHttpInfo: Create the specified model.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayCreateToken $model VodaPayGatewayCreateToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenCreate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function tokenCreateWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenCreate'][0],
    ): array {
        $request = $this->tokenCreateRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * tokenCreateAsync: Create the specified model.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayCreateToken $model VodaPayGatewayCreateToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenCreateAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenCreate'][0],
    ): PromiseInterface {
        return $this->tokenCreateAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * tokenCreateAsyncWithHttpInfo: Create the specified model.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayCreateToken $model VodaPayGatewayCreateToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenCreateAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenCreate'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenResponse';
        $request = $this->tokenCreateRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenCreate'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayCreateToken $model VodaPayGatewayCreateToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenCreateRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenCreate'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling tokenCreate'
            );
        }



        $resourcePath = '/v2/Token/Create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * tokenList: Get a list of tokens.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayListToken $model VodaPayGatewayListToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse
     */
    public function tokenList(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenList'][0],
    ): mixed {
        list($response) = $this->tokenListWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * tokenListWithHttpInfo: Get a list of tokens.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayListToken $model VodaPayGatewayListToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse|\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function tokenListWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenList'][0],
    ): array {
        $request = $this->tokenListRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * tokenListAsync: Get a list of tokens.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayListToken $model VodaPayGatewayListToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenListAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenList'][0],
    ): PromiseInterface {
        return $this->tokenListAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * tokenListAsyncWithHttpInfo: Get a list of tokens.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayListToken $model VodaPayGatewayListToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenListAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenList'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayTokenListResponse';
        $request = $this->tokenListRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenList'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayListToken $model VodaPayGatewayListToken. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test Is testing (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function tokenListRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['tokenList'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling tokenList'
            );
        }



        $resourcePath = '/v2/Token/List';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
