<?php

declare(strict_types=1);

/**
 * VodaPay Gateway
 *
 * Enabling ecommerce merchants to accept online payments from customers.
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VodaPayGatewayClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use VodaPayGatewayClient\ApiException;
use VodaPayGatewayClient\Configuration;
use VodaPayGatewayClient\HeaderSelector;
use VodaPayGatewayClient\ObjectSerializer;

class WalletApi
{
    /**
     * @var array<string, list<string>>
     */
    public const contentTypes = [
        'digitalWalletBlock' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'digitalWalletUnblock' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        private readonly ClientInterface $client = new Client(),
        private readonly Configuration $config = new Configuration(),
        private readonly HeaderSelector $headerSelector = new HeaderSelector(),
        private int $hostIndex = 0,
    ) {
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * digitalWalletBlock: Initializes a new instance of the DigitalWalletController class.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletBlock'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse|\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse
     */
    public function digitalWalletBlock(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletBlock'][0],
    ): mixed {
        list($response) = $this->digitalWalletBlockWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * digitalWalletBlockWithHttpInfo: Initializes a new instance of the DigitalWalletController class.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletBlock'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse|\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function digitalWalletBlockWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletBlock'][0],
    ): array {
        $request = $this->digitalWalletBlockRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * digitalWalletBlockAsync: Initializes a new instance of the DigitalWalletController class.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletBlockAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletBlock'][0],
    ): PromiseInterface {
        return $this->digitalWalletBlockAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * digitalWalletBlockAsyncWithHttpInfo: Initializes a new instance of the DigitalWalletController class.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletBlockAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletBlock'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\VodaPayGatewayDigitalWalletResponse';
        $request = $this->digitalWalletBlockRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'digitalWalletBlock'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletBlockRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletBlock'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling digitalWalletBlock'
            );
        }



        $resourcePath = '/v2/DigitalWallet/Block';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * digitalWalletUnblock: Unblock wallet.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletUnblock'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return \VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel|\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel
     */
    public function digitalWalletUnblock(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletUnblock'][0],
    ): mixed {
        list($response) = $this->digitalWalletUnblockWithHttpInfo($model, $api_key, $test, $contentType);

        return $response;
    }

    /**
     * digitalWalletUnblockWithHttpInfo: Unblock wallet.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletUnblock'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response
     * @throws GuzzleException
     * @throws \InvalidArgumentException
     *
     * @return array{
     *     \VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel|\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel,
     *     int,
     *     list<string>,
     * } Array of response body, status, and response headers
     */
    public function digitalWalletUnblockWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletUnblock'][0],
    ): array {
        $request = $this->digitalWalletUnblockRequest($model, $api_key, $test, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * digitalWalletUnblockAsync: Unblock wallet.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletUnblock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletUnblockAsync(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletUnblock'][0],
    ): PromiseInterface {
        return $this->digitalWalletUnblockAsyncWithHttpInfo($model, $api_key, $test, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * digitalWalletUnblockAsyncWithHttpInfo: Unblock wallet.
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletUnblock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletUnblockAsyncWithHttpInfo(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletUnblock'][0],
    ): PromiseInterface {
        $returnType = '\VodaPayGatewayClient\Model\PaymentDigitalWalletResponseModel';
        $request = $this->digitalWalletUnblockRequest($model, $api_key, $test, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'digitalWalletUnblock'
     *
     * @param  \VodaPayGatewayClient\Model\VodaPayGatewayDigitalWallet $model VodaPayGatewayDigitalWallet. (required)
     * @param  string $api_key The API key. (optional)
     * @param  bool $test if set to true [is testing]. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['digitalWalletUnblock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     */
    public function digitalWalletUnblockRequest(
        mixed $model,
        mixed $api_key = null,
        mixed $test = false,
        string $contentType = self::contentTypes['digitalWalletUnblock'][0],
    ): Request {
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling digitalWalletUnblock'
            );
        }



        $resourcePath = '/v2/DigitalWallet/Unblock';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($api_key !== null) {
            $headerParams['api-key'] = ObjectSerializer::toHeaderValue($api_key);
        }

        // header params
        if ($test !== null) {
            $headerParams['test'] = ObjectSerializer::toHeaderValue($test);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($model));
            } else {
                $httpBody = $model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
