<?php

declare(strict_types=1);

/**
 * VodaPay Gateway
 *
 * Enabling ecommerce merchants to accept online payments from customers.
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VodaPayGatewayClient;

class ApiException extends \Exception
{
    /**
     * The deserialized response object
     */
    protected mixed $responseObject = null;

    /**
     * Constructor
     *
     * @param string                     $message         Error message
     * @param int                        $code            HTTP status code
     * @param null|array<string, string> $responseHeaders HTTP response header
     * @param null|object|string         $responseBody    HTTP decoded body of the server response either as \stdClass or string
     */
    public function __construct(
        string $message = '',
        int $code = 0,
        private readonly ?array $responseHeaders = [],
        private readonly null|object|string $responseBody = null,
    ) {
        parent::__construct($message, $code);
    }

    /**
     * Gets the HTTP response header
     *
     * @return null|array<string, string> HTTP response header
     */
    public function getResponseHeaders(): ?array
    {
        return $this->responseHeaders;
    }

    /**
     * Gets the HTTP body of the server response either as Json or string
     *
     * @return null|object|string HTTP body of the server response either as \stdClass or string
     */
    public function getResponseBody(): null|object|string
    {
        return $this->responseBody;
    }

    /**
     * Sets the deserialized response object (during deserialization)
     *
     * @param mixed $obj Deserialized response object
     */
    public function setResponseObject(mixed $obj): static
    {
        $this->responseObject = $obj;

        return $this;
    }

    /**
     * Gets the deserialized response object (during deserialization)
     *
     * @return mixed the deserialized response object
     */
    public function getResponseObject(): mixed
    {
        return $this->responseObject;
    }
}
